export const INITIATE_ANSWER = "INITIATE_ANSWER";
export const INITIATE_OFFER = "INITIATE_OFFER";
export const ADD_ANSWER = "ADD_ANSWER";
export const GET_ICE_CANDIDATE = "GET_ICE_CANDIDATE";
export const REQUEST_OFFER = "REQUEST_OFFER";
export const DISCONNECTED = "DISCONNECTED";
